name: terraform

on: [push]

jobs:
  terraform: 
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
    - name: init
      run: terraform init
    - name: validate
      run: terraform validate
    - name: format
      run: terraform fmt -check
    - name: plan
      run: terraform plan
    
#